trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: Release
  projectPath: src/wolfpage-apii.Api/wolfpage-api.Api.csproj
  appName: wolfware-api

steps:
- task: UseDotNet@2
  displayName: Use .NET SDK
  inputs:
    packageType: sdk
    version: 10.0.x

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: $(projectPath)

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: $(projectPath)
    arguments: --configuration $(buildConfiguration) --no-restore

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: $(projectPath)
    arguments: --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
    zipAfterPublish: true

- task: AzureWebApp@1
  displayName: Deploy to Azure App Service
  inputs:
    azureSubscription: 'Wolfware subscription(f221d359-1391-4974-aaba-6cf373b7811a)'
    appType: webAppLinux
    appName: $(appName)
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'